name: "TWIN Node 102"

services:
  db:
    image: mysql:8.4.7
    container_name: mysql8_container
    hostname: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: twin
      MYSQL_PASSWORD: twin
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h 127.0.0.1 -u twin -ptwin --silent || exit 1",
        ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ../../common/init:/docker-entrypoint-initdb.d

  twin-node:
    image: twinfoundation/twin-node:0.9.1-next.2
    container_name: twin_node
    hostname: node
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    env_file:
      - ../../common/.env.local
      - ./.env.extensions
      - ./.env.multitenant
    volumes:
      - twin_data:/var/lib/twin
      - ../../common/.env.local.bootstrap:/app/.env.local.bootstrap
      - ../../common/.env.bootstrap-legacy:/app/.env.bootstrap-legacy
      - ./apps/dataspace-example-app:/app/node_modules/@twin-community.org/dataspace-example-app
      - ./apps/consumer-client:/app/node_modules/@twin-community.org/consumer-client
      - ./tutorial-data/provider.json:/app/provider.json
      - ./tutorial-data/consumer.json:/app/consumer.json
volumes:
  mysql_data:
  twin_data:
